### ISSUE TITLE
Questions on features:

### ISSUE THREAD

**Issue by seanbperiod** [daemionfox/patreon-feed#9]
Will this allow me to create an RSS feed that includes subscriber-enabled posts? 

I'm curious if I can add a custom Patreon feed to Apple Podcasts that includes paying-subscriber-enabled videos so I can easily watch from Apple TV - using this script. 

(It's surprising to me that Patreon hasn't enabled this ability for creators.)

Thanks!

**Comment by daemionfox** [comment]
So yes, however, as usual, there are caveats.

This software has been untouched for a few years, so you use it at your own risk.  
That said, I was able to use it to generate an ongoing feed of text data from the posts.

Just the text data, not image data or video.  That may have changed since...  2021 when it was last touched.  You're going to have to try it and see if you can pull more information from the feed than just the text.
